### PR TITLE
Bump up to gherkin 4.0

### PR DESCRIPTION
**Pull request by norekinc**
This PR includes:
1. Update gherkin version to 4.0
4.0 is a major release. Updated CityBuilder regarding major changes, gherkin change details: https://github.com/cucumber/gherkin/blob/master/CHANGELOG.md

2. Included fixes from @Kenny Gilles, to show description and background in yard

3. A tiny feature: excluding scenarios from being documented by using cucumber tags. Please, have a look to updated README for more details.

### CODE REVIEW

**Comment by norekinc** [comment]
I could also add tests, but I don't see any existing ones :(

**Comment by tk8817** [comment]
@burtlo would you be kind enough to push a release to ruby-gems?

**Comment by burtlo** [comment]
Yes. I would love to release it. I'm installing the Ruby version associated with the project, installing dependencies and running it to make sure it all works.

Which brings up the next question for me: should we update the Ruby version associated with the git repository?

**Comment by burtlo** [comment]
I merged this and I am getting errors when running it:

```
$ rake gendoc
/Users/franklinwebber/source/yard-cucumber/lib/cucumber/city_builder.rb:93:in `feature': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/franklinwebber/source/yard-cucumber/lib/cucumber/city_builder.rb:32:in `ast'
	from /Users/franklinwebber/source/yard-cucumber/lib/yard/parser/cucumber/feature.rb:38:in `parse'
	from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/yard-0.9.5/lib/yard/parser/source_parser.rb:440:in `parse'
```

**Comment by burtlo** [comment]
I found the issue is with the `examples/empty.feature`:
```ruby
# This is a feature that has not been written
# However, I don't want parser to fail when reaching this file
```

Within the `CityBuilder` I'll add some code to skip when the document contains no feature.

**Comment by burtlo** [comment]
I noticed now that `rake gendoc` completes successfully but then I don't see all the appropriate files in the `doc` directory (i.e. `doc/index.html`). So I think there was a failure in the command execution so I ran the command outside of rake and receiving the following:

```
$ yardoc -e ./lib/yard-cucumber.rb 'example/**/*' --debug
...
[debug]: Generating asset feature_list.html
[debug]: Serializing to doc/feature_list.html
[debug]: Generating asset tag_list.html
[debug]: Serializing to doc/tag_list.html
/Users/franklinwebber/source/yard-cucumber/lib/templates/default/fulldoc/html/setup.rb:146:in `class_list': wrong number of arguments (2 for 0..1) (ArgumentError)
	from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/yard-0.9.5/templates/default/fulldoc/html/setup.rb:236:in `block (2 levels) in class_list'
	from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/yard-0.9.5/templates/default/fulldoc/html/setup.rb:185:in `nest'
	from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/yard-0.9.5/templates/default/fulldoc/html/setup.rb:235:in `block in class_list'
```

**Comment by burtlo** [comment]
Looking at YARD I found that `class_list` method now needs an additional parameter which I have included:

```ruby
def class_list(root = Registry.root, tree = TreeContext.new)
  return super unless root == Registry.root
  cucumber_namespace = YARD::CodeObjects::Cucumber::CUCUMBER_NAMESPACE
  root.instance_eval { children.delete cucumber_namespace }
  out = super(root)
  root.instance_eval { children.push cucumber_namespace }
  out
end
```

And that causes everything to work. However, it seems like the output is a little strange:

Features:



Tags:



I think this could be an HTML element issue or CSS issue.

**Comment by burtlo** [comment]
As I suspected, there were some layouts and styles in the menus that I have addressed. I need to make those changes as well for step definitions and transforms.

The last issue that I want to address is that the 'Class List' tab is the default to appear when opening the index.html. I would like that to be features.

**Comment by burtlo** [comment]
Fixes to Feature Directory formatting and collapsing: 4ae2bc24ec866aec4e646d48b2f6e1fa70b1ef53

Fixes to the nav menu to show the appropriate menu if it has been created: 05615b511b893cb4fb3455587d61cf8dfdeeeb51

**Comment by burtlo** [comment]
Alright I think that the gem is now ready for release.

**Pull request merged**
